export const mockProducts = [
  // ============ LARGE FORMAT PRINTING ============
  
  // Coroplast Signs / Easels
  {
    _id: "lf001",
    title: "Coroplast Yard Sign - 18\" x 24\"",
    image: ["/assets/colors/7.jpg"],
    price: 25.00,
    off_price: 35.00,
    discount: 29,
    discountPercentage: 29,
    set: 1,
    stock: 150,
    description: "Durable corrugated plastic sign. Weather-resistant for outdoor use. Includes H-stake.",
    size: "18\" x 24\"",
    category: "largeformat",
    subCategory: "coroplast",
    shape: "rectangular",
  },
  {
    _id: "lf002",
    title: "Coroplast Sign with Easel - 24\" x 36\"",
    image: ["/assets/colors/7.jpg"],
    price: 45.00,
    off_price: 60.00,
    discount: 25,
    discountPercentage: 25,
    set: 1,
    stock: 100,
    description: "Large coroplast sign with sturdy metal easel stand. Perfect for events and presentations.",
    size: "24\" x 36\"",
    category: "largeformat",
    subCategory: "coroplast",
    shape: "rectangular",
  },

  // Foam Core Sign / Selfie Frames
  {
    _id: "lf003",
    title: "Foam Core Sign - 24\" x 36\"",
    image: ["/assets/colors/7.jpg"],
    price: 35.00,
    off_price: 48.00,
    discount: 27,
    discountPercentage: 27,
    set: 1,
    stock: 120,
    description: "Lightweight foam core board sign. Great for indoor displays and presentations.",
    size: "24\" x 36\"",
    category: "largeformat",
    subCategory: "foamcore",
    shape: "rectangular",
  },
  {
    _id: "lf004",
    title: "Custom Selfie Frame - 30\" x 40\"",
    image: ["/assets/colors/7.jpg"],
    price: 65.00,
    off_price: 85.00,
    discount: 24,
    discountPercentage: 24,
    set: 1,
    stock: 75,
    description: "Fun foam core selfie frame with custom design. Perfect for parties and events.",
    size: "30\" x 40\"",
    category: "largeformat",
    subCategory: "foamcore",
    shape: "rectangular",
  },

  // Custom Shape Signs
  {
    _id: "lf005",
    title: "Custom Shape Sign - Small",
    image: ["/assets/colors/7.jpg"],
    price: 55.00,
    off_price: 75.00,
    discount: 27,
    discountPercentage: 27,
    set: 1,
    stock: 80,
    description: "Die-cut custom shaped sign. Any shape, full color printing on durable material.",
    size: "Up to 24\"",
    category: "largeformat",
    subCategory: "customshape",
    shape: "custom",
  },
  {
    _id: "lf006",
    title: "Custom Shape Sign - Large",
    image: ["/assets/colors/7.jpg"],
    price: 95.00,
    off_price: 125.00,
    discount: 24,
    discountPercentage: 24,
    set: 1,
    stock: 60,
    description: "Large die-cut custom shaped sign. Stand out with unique shapes and designs.",
    size: "Up to 48\"",
    category: "largeformat",
    subCategory: "customshape",
    shape: "custom",
  },

  // Vinyl Banners
  {
    _id: "lf007",
    title: "Vinyl Banner - 2ft x 5ft",
    image: ["/assets/colors/5.jpg"],
    price: 40.00,
    off_price: 55.00,
    discount: 27,
    discountPercentage: 27,
    set: 1,
    stock: 100,
    description: "13 oz full color vinyl banner. Hemmed & grommeted. Weather resistant.",
    size: "2ft x 5ft",
    category: "largeformat",
    subCategory: "banner",
    shape: "rectangular",
  },
  {
    _id: "lf008",
    title: "Vinyl Banner - 3ft x 6ft",
    image: ["/assets/colors/5.jpg"],
    price: 72.00,
    off_price: 95.00,
    discount: 24,
    discountPercentage: 24,
    set: 1,
    stock: 85,
    description: "13 oz vinyl banner. Perfect for events, storefronts, and outdoor advertising.",
    size: "3ft x 6ft",
    category: "largeformat",
    subCategory: "banner",
    shape: "rectangular",
  },
  {
    _id: "lf009",
    title: "Vinyl Banner - 4ft x 8ft",
    image: ["/assets/colors/5.jpg"],
    price: 128.00,
    off_price: 170.00,
    discount: 25,
    discountPercentage: 25,
    set: 1,
    stock: 60,
    description: "Large 13 oz vinyl banner. High-impact outdoor advertising solution.",
    size: "4ft x 8ft",
    category: "largeformat",
    subCategory: "banner",
    shape: "rectangular",
  },
  {
    _id: "lf010",
    title: "Vinyl Banner - 5ft x 10ft",
    image: ["/assets/colors/5.jpg"],
    price: 200.00,
    off_price: 275.00,
    discount: 27,
    discountPercentage: 27,
    set: 1,
    stock: 45,
    description: "Extra large vinyl banner. Maximum visibility for buildings and large events.",
    size: "5ft x 10ft",
    category: "largeformat",
    subCategory: "banner",
    shape: "rectangular",
  },

  // Retractable / Roll up Banners
  {
    _id: "lf011",
    title: "Retractable Banner - Economy Stand",
    image: ["/assets/colors/5.jpg"],
    price: 190.00,
    off_price: 250.00,
    discount: 24,
    discountPercentage: 24,
    set: 1,
    stock: 60,
    description: "Portable retractable banner with economy stand. 31.5\" W x 78.7\" H. Easy setup.",
    size: "31.5\" x 78.7\"",
    category: "largeformat",
    subCategory: "retractable",
    shape: "rectangular",
  },
  {
    _id: "lf012",
    title: "Retractable Banner - Premium Stand",
    image: ["/assets/colors/5.jpg"],
    price: 240.00,
    off_price: 320.00,
    discount: 25,
    discountPercentage: 25,
    set: 1,
    stock: 40,
    description: "Professional retractable banner with premium stand. 33.5\" W x 78.7\" H.",
    size: "33.5\" x 78.7\"",
    category: "largeformat",
    subCategory: "retractable",
    shape: "rectangular",
  },

  // Posters (Glossy or Matte)
  {
    _id: "lf013",
    title: "Poster 18\" x 24\" - Glossy",
    image: ["/assets/colors/7.jpg"],
    price: 16.00,
    off_price: 22.00,
    discount: 27,
    discountPercentage: 27,
    set: 1,
    stock: 200,
    description: "High-quality glossy poster. Vibrant colors, perfect for indoor display.",
    size: "18\" x 24\"",
    category: "largeformat",
    subCategory: "poster",
    shape: "rectangular",
  },
  {
    _id: "lf014",
    title: "Poster 24\" x 36\" - Glossy",
    image: ["/assets/colors/7.jpg"],
    price: 22.00,
    off_price: 30.00,
    discount: 27,
    discountPercentage: 27,
    set: 1,
    stock: 150,
    description: "Large glossy poster. Professional quality for presentations and events.",
    size: "24\" x 36\"",
    category: "largeformat",
    subCategory: "poster",
    shape: "rectangular",
  },
  {
    _id: "lf015",
    title: "Poster 36\" x 48\" - Glossy",
    image: ["/assets/colors/7.jpg"],
    price: 56.00,
    off_price: 75.00,
    discount: 25,
    discountPercentage: 25,
    set: 1,
    stock: 80,
    description: "Extra large glossy poster. Eye-catching display for retail and events.",
    size: "36\" x 48\"",
    category: "largeformat",
    subCategory: "poster",
    shape: "rectangular",
  },
  {
    _id: "lf016",
    title: "Poster 24\" x 36\" - Matte",
    image: ["/assets/colors/7.jpg"],
    price: 18.00,
    off_price: 25.00,
    discount: 28,
    discountPercentage: 28,
    set: 1,
    stock: 140,
    description: "Matte finish poster. No glare, perfect for photography and art displays.",
    size: "24\" x 36\"",
    category: "largeformat",
    subCategory: "poster",
    shape: "rectangular",
  },

  // Backdrop / Step & Repeat Banners
  {
    _id: "lf017",
    title: "Step & Repeat Backdrop - 8ft x 8ft",
    image: ["/assets/colors/5.jpg"],
    price: 180.00,
    off_price: 240.00,
    discount: 25,
    discountPercentage: 25,
    set: 1,
    stock: 35,
    description: "Professional step and repeat banner for events. Includes stand and carry bag.",
    size: "8ft x 8ft",
    category: "largeformat",
    subCategory: "backdrop",
    shape: "rectangular",
  },
  {
    _id: "lf018",
    title: "Step & Repeat Backdrop - 10ft x 8ft",
    image: ["/assets/colors/5.jpg"],
    price: 220.00,
    off_price: 295.00,
    discount: 25,
    discountPercentage: 25,
    set: 1,
    stock: 25,
    description: "Large step and repeat backdrop. Perfect for red carpet events and photo ops.",
    size: "10ft x 8ft",
    category: "largeformat",
    subCategory: "backdrop",
    shape: "rectangular",
  },

  // Fatheads
  {
    _id: "lf019",
    title: "Custom Fathead - Life Size",
    image: ["/assets/colors/7.jpg"],
    price: 85.00,
    off_price: 115.00,
    discount: 26,
    discountPercentage: 26,
    set: 1,
    stock: 50,
    description: "Life-size custom cutout fathead. Removable and reusable adhesive backing.",
    size: "Up to 6ft tall",
    category: "largeformat",
    subCategory: "fathead",
    shape: "custom",
  },
  {
    _id: "lf020",
    title: "Custom Fathead - Mini",
    image: ["/assets/colors/7.jpg"],
    price: 35.00,
    off_price: 48.00,
    discount: 27,
    discountPercentage: 27,
    set: 1,
    stock: 80,
    description: "Mini fathead cutout. Perfect for desks, walls, and lockers.",
    size: "Up to 2ft",
    category: "largeformat",
    subCategory: "fathead",
    shape: "custom",
  },

  // Custom Standees
  {
    _id: "lf021",
    title: "Custom Standee - Life Size",
    image: ["/assets/colors/7.jpg"],
    price: 95.00,
    off_price: 125.00,
    discount: 24,
    discountPercentage: 24,
    set: 1,
    stock: 40,
    description: "Free-standing cardboard cutout. Die-cut to your custom shape with easel back.",
    size: "Up to 6ft tall",
    category: "largeformat",
    subCategory: "standee",
    shape: "custom",
  },
  {
    _id: "lf022",
    title: "Custom Standee - Tabletop",
    image: ["/assets/colors/7.jpg"],
    price: 28.00,
    off_price: 38.00,
    discount: 26,
    discountPercentage: 26,
    set: 1,
    stock: 100,
    description: "Tabletop standee cutout. Perfect for displays and promotions.",
    size: "Up to 18\" tall",
    category: "largeformat",
    subCategory: "standee",
    shape: "custom",
  },

  // Blue Prints
  {
    _id: "lf023",
    title: "Blueprint - 24\" x 36\"",
    image: ["/assets/colors/7.jpg"],
    price: 8.00,
    off_price: 12.00,
    discount: 33,
    discountPercentage: 33,
    set: 1,
    stock: 200,
    description: "High-quality blueprint printing. Standard 20lb bond paper.",
    size: "24\" x 36\"",
    category: "largeformat",
    subCategory: "blueprint",
    shape: "rectangular",
  },
  {
    _id: "lf024",
    title: "Blueprint - 36\" x 48\"",
    image: ["/assets/colors/7.jpg"],
    price: 14.00,
    off_price: 20.00,
    discount: 30,
    discountPercentage: 30,
    set: 1,
    stock: 150,
    description: "Large format blueprint. Professional quality for construction and engineering.",
    size: "36\" x 48\"",
    category: "largeformat",
    subCategory: "blueprint",
    shape: "rectangular",
  },

  // Canvas
  {
    _id: "lf025",
    title: "Canvas Print - 16\" x 20\"",
    image: ["/assets/colors/7.jpg"],
    price: 55.00,
    off_price: 75.00,
    discount: 27,
    discountPercentage: 27,
    set: 1,
    stock: 90,
    description: "Gallery-wrapped canvas print. Museum quality with wooden frame.",
    size: "16\" x 20\"",
    category: "largeformat",
    subCategory: "canvas",
    shape: "rectangular",
  },
  {
    _id: "lf026",
    title: "Canvas Print - 24\" x 36\"",
    image: ["/assets/colors/7.jpg"],
    price: 95.00,
    off_price: 125.00,
    discount: 24,
    discountPercentage: 24,
    set: 1,
    stock: 70,
    description: "Large canvas print. Professional gallery wrap with 1.5\" stretcher bars.",
    size: "24\" x 36\"",
    category: "largeformat",
    subCategory: "canvas",
    shape: "rectangular",
  },
  {
    _id: "lf027",
    title: "Canvas Print - 30\" x 40\"",
    image: ["/assets/colors/7.jpg"],
    price: 135.00,
    off_price: 180.00,
    discount: 25,
    discountPercentage: 25,
    set: 1,
    stock: 50,
    description: "Extra large canvas. Statement piece for home or office decor.",
    size: "30\" x 40\"",
    category: "largeformat",
    subCategory: "canvas",
    shape: "rectangular",
  },

  // A-Frame / Sidewalk Sign Frames
  {
    _id: "lf028",
    title: "A-Frame Sidewalk Sign - 24\" x 36\"",
    image: ["/assets/colors/7.jpg"],
    price: 85.00,
    off_price: 115.00,
    discount: 26,
    discountPercentage: 26,
    set: 1,
    stock: 65,
    description: "Double-sided A-frame sign. Metal frame with interchangeable printed inserts.",
    size: "24\" x 36\"",
    category: "largeformat",
    subCategory: "aframe",
    shape: "rectangular",
  },
  {
    _id: "lf029",
    title: "Sidewalk Sign - Economy",
    image: ["/assets/colors/7.jpg"],
    price: 55.00,
    off_price: 75.00,
    discount: 27,
    discountPercentage: 27,
    set: 1,
    stock: 80,
    description: "Economy sidewalk sign. Lightweight but durable for storefront use.",
    size: "24\" x 32\"",
    category: "largeformat",
    subCategory: "aframe",
    shape: "rectangular",
  },

  // Lamination / Dry Erase
  {
    _id: "lf030",
    title: "Laminated Poster - 24\" x 36\"",
    image: ["/assets/colors/7.jpg"],
    price: 32.00,
    off_price: 45.00,
    discount: 29,
    discountPercentage: 29,
    set: 1,
    stock: 120,
    description: "3mil laminated poster. Protected finish for durability.",
    size: "24\" x 36\"",
    category: "largeformat",
    subCategory: "lamination",
    shape: "rectangular",
  },
  {
    _id: "lf031",
    title: "Dry Erase Board - 24\" x 36\"",
    image: ["/assets/colors/7.jpg"],
    price: 65.00,
    off_price: 85.00,
    discount: 24,
    discountPercentage: 24,
    set: 1,
    stock: 75,
    description: "Custom printed dry erase board. Write-on, wipe-off surface with aluminum frame.",
    size: "24\" x 36\"",
    category: "largeformat",
    subCategory: "dryerase",
    shape: "rectangular",
  },

  // Giant Checks
  {
    _id: "lf032",
    title: "Giant Check - 24\" x 48\"",
    image: ["/assets/colors/7.jpg"],
    price: 45.00,
    off_price: 60.00,
    discount: 25,
    discountPercentage: 25,
    set: 1,
    stock: 60,
    description: "Oversized novelty check. Perfect for ceremonies and presentations.",
    size: "24\" x 48\"",
    category: "largeformat",
    subCategory: "giantcheck",
    shape: "rectangular",
  },
  {
    _id: "lf033",
    title: "Giant Check - 30\" x 60\"",
    image: ["/assets/colors/7.jpg"],
    price: 65.00,
    off_price: 85.00,
    discount: 24,
    discountPercentage: 24,
    set: 1,
    stock: 45,
    description: "Extra large ceremonial check. Makes a big impression at events.",
    size: "30\" x 60\"",
    category: "largeformat",
    subCategory: "giantcheck",
    shape: "rectangular",
  },

  // Car Magnets / Custom Shape Magnets
  {
    _id: "lf034",
    title: "Car Magnet - 12\" x 18\"",
    image: ["/assets/colors/12.jpg"],
    price: 28.00,
    off_price: 38.00,
    discount: 26,
    discountPercentage: 26,
    set: 1,
    stock: 150,
    description: "Vehicle door magnet. 30mil magnetic material, weatherproof.",
    size: "12\" x 18\"",
    category: "largeformat",
    subCategory: "carmagnet",
    shape: "rectangular",
  },
  {
    _id: "lf035",
    title: "Car Magnet - 18\" x 24\"",
    image: ["/assets/colors/12.jpg"],
    price: 42.00,
    off_price: 56.00,
    discount: 25,
    discountPercentage: 25,
    set: 1,
    stock: 100,
    description: "Large car door magnet. High-impact mobile advertising.",
    size: "18\" x 24\"",
    category: "largeformat",
    subCategory: "carmagnet",
    shape: "rectangular",
  },
  {
    _id: "lf036",
    title: "Custom Shape Magnet",
    image: ["/assets/colors/12.jpg"],
    price: 35.00,
    off_price: 48.00,
    discount: 27,
    discountPercentage: 27,
    set: 1,
    stock: 80,
    description: "Die-cut custom shaped magnet. Any shape up to 12\" in any direction.",
    size: "Custom",
    category: "largeformat",
    subCategory: "carmagnet",
    shape: "custom",
  },

  // Cut Vinyl & Speciality Vinyl
  {
    _id: "lf037",
    title: "Cut Vinyl Lettering - Small",
    image: ["/assets/colors/13.jpg"],
    price: 15.00,
    off_price: 22.00,
    discount: 32,
    discountPercentage: 32,
    set: 1,
    stock: 200,
    description: "Premium cut vinyl letters. Indoor/outdoor use, easy application.",
    size: "Up to 6\" tall",
    category: "largeformat",
    subCategory: "vinyl",
    shape: "custom",
  },
  {
    _id: "lf038",
    title: "Cut Vinyl Lettering - Large",
    image: ["/assets/colors/13.jpg"],
    price: 45.00,
    off_price: 60.00,
    discount: 25,
    discountPercentage: 25,
    set: 1,
    stock: 120,
    description: "Large format cut vinyl. Perfect for vehicle graphics and signage.",
    size: "Up to 24\" tall",
    category: "largeformat",
    subCategory: "vinyl",
    shape: "custom",
  },
  {
    _id: "lf039",
    title: "Specialty Reflective Vinyl",
    image: ["/assets/colors/13.jpg"],
    price: 32.00,
    off_price: 45.00,
    discount: 29,
    discountPercentage: 29,
    set: 1,
    stock: 90,
    description: "High-visibility reflective vinyl. Safety compliant for vehicles and signage.",
    size: "Per sq ft",
    category: "largeformat",
    subCategory: "vinyl",
    shape: "custom",
  },

  // Window Cling
  {
    _id: "lf040",
    title: "Window Cling - 12\" x 18\"",
    image: ["/assets/colors/14.jpg"],
    price: 18.00,
    off_price: 25.00,
    discount: 28,
    discountPercentage: 28,
    set: 1,
    stock: 180,
    description: "Static cling window decal. Removable and reusable, no adhesive.",
    size: "12\" x 18\"",
    category: "largeformat",
    subCategory: "windowcling",
    shape: "rectangular",
  },
  {
    _id: "lf041",
    title: "Window Cling - 18\" x 24\"",
    image: ["/assets/colors/14.jpg"],
    price: 28.00,
    off_price: 38.00,
    discount: 26,
    discountPercentage: 26,
    set: 1,
    stock: 140,
    description: "Large window cling. Perfect for storefront promotions and displays.",
    size: "18\" x 24\"",
    category: "largeformat",
    subCategory: "windowcling",
    shape: "rectangular",
  },

  // ============ SMALL FORMAT PUBLICATION ============
  
  // Business Cards
  {
    _id: "bc001",
    title: "Business Cards - UV Hi-Gloss (100 cards)",
    image: ["/assets/colors/1.jpg"],
    price: 28.00,
    off_price: 40.00,
    discount: 30,
    discountPercentage: 30,
    set: 100,
    stock: 500,
    description: "Premium UV Hi-Gloss business cards with vibrant colors. 16pt cardstock, one-sided printing.",
    size: "3.5 x 2 inches",
    category: "printing",
    subCategory: "visitingcard",
    shape: "rectangular",
  },
  {
    _id: "bc002",
    title: "Business Cards - UV Hi-Gloss (250 cards)",
    image: ["/assets/colors/1.jpg"],
    price: 40.00,
    off_price: 55.00,
    discount: 27,
    discountPercentage: 27,
    set: 250,
    stock: 400,
    description: "Premium UV Hi-Gloss business cards. 16pt cardstock, one-sided printing. Best value!",
    size: "3.5 x 2 inches",
    category: "printing",
    subCategory: "visitingcard",
    shape: "rectangular",
  },
  {
    _id: "bc003",
    title: "Business Cards - Non-Gloss Writable (1000 cards)",
    image: ["/assets/colors/1.jpg"],
    price: 58.00,
    off_price: 80.00,
    discount: 28,
    discountPercentage: 28,
    set: 1000,
    stock: 300,
    description: "Writable non-gloss business cards. Perfect for writing notes. 16pt cardstock.",
    size: "3.5 x 2 inches",
    category: "printing",
    subCategory: "visitingcard",
    shape: "rectangular",
  },
  {
    _id: "bc004",
    title: "Plastic Business Cards - White (100 cards)",
    image: ["/assets/colors/1.jpg"],
    price: 158.10,
    off_price: 220.00,
    discount: 28,
    discountPercentage: 28,
    set: 100,
    stock: 200,
    description: "Durable plastic business cards with rounded corners. Waterproof and long-lasting.",
    size: "3.5 x 2 inches",
    category: "printing",
    subCategory: "visitingcard",
    shape: "rectangular",
  },
  {
    _id: "bc005",
    title: "Business Cards - Two-Sided (500 cards)",
    image: ["/assets/colors/1.jpg"],
    price: 54.00,
    off_price: 72.00,
    discount: 25,
    discountPercentage: 25,
    set: 500,
    stock: 350,
    description: "Double-sided UV Hi-Gloss business cards. Make an impression on both sides.",
    size: "3.5 x 2 inches",
    category: "printing",
    subCategory: "visitingcard",
    shape: "rectangular",
  },

  // Business Card Magnets
  {
    _id: "bcm001",
    title: "Business Card Magnet (100 pcs)",
    image: ["/assets/colors/1.jpg"],
    price: 65.00,
    off_price: 85.00,
    discount: 24,
    discountPercentage: 24,
    set: 100,
    stock: 200,
    description: "Full color business card magnets. Stick your message on any magnetic surface.",
    size: "3.5 x 2 inches",
    category: "printing",
    subCategory: "businesscardmagnet",
    shape: "rectangular",
  },
  {
    _id: "bcm002",
    title: "Business Card Magnet (250 pcs)",
    image: ["/assets/colors/1.jpg"],
    price: 120.00,
    off_price: 160.00,
    discount: 25,
    discountPercentage: 25,
    set: 250,
    stock: 150,
    description: "Bulk business card magnets. Great for promotions and giveaways.",
    size: "3.5 x 2 inches",
    category: "printing",
    subCategory: "businesscardmagnet",
    shape: "rectangular",
  },

  // Postcards & EDDM
  {
    _id: "pc001",
    title: "Postcards 4\" x 6\" (100 pcs)",
    image: ["/assets/colors/8.jpg"],
    price: 24.00,
    off_price: 32.00,
    discount: 25,
    discountPercentage: 25,
    set: 100,
    stock: 300,
    description: "Full color postcards. 14pt cardstock, UV gloss coating.",
    size: "4\" x 6\"",
    category: "printing",
    subCategory: "postcard",
    shape: "rectangular",
  },
  {
    _id: "pc002",
    title: "Postcards 5\" x 7\" (250 pcs)",
    image: ["/assets/colors/8.jpg"],
    price: 55.00,
    off_price: 75.00,
    discount: 27,
    discountPercentage: 27,
    set: 250,
    stock: 250,
    description: "Large postcards. Perfect for direct mail campaigns and announcements.",
    size: "5\" x 7\"",
    category: "printing",
    subCategory: "postcard",
    shape: "rectangular",
  },
  {
    _id: "pc003",
    title: "EDDM Postcards 6.5\" x 9\" (1000 pcs)",
    image: ["/assets/colors/8.jpg"],
    price: 180.00,
    off_price: 240.00,
    discount: 25,
    discountPercentage: 25,
    set: 1000,
    stock: 150,
    description: "Every Door Direct Mail postcards. Reach every home in your area.",
    size: "6.5\" x 9\"",
    category: "printing",
    subCategory: "eddm",
    shape: "rectangular",
  },

  // Brochures
  {
    _id: "br001",
    title: "Brochure - Tri-Fold 8.5\" x 11\" (100 pcs) - 28lb",
    image: ["/assets/colors/9.jpg"],
    price: 45.00,
    off_price: 60.00,
    discount: 25,
    discountPercentage: 25,
    set: 100,
    stock: 200,
    description: "Tri-fold brochure on 28lb paper. Economical choice for informational materials.",
    size: "8.5\" x 11\"",
    category: "printing",
    subCategory: "brochure",
    shape: "rectangular",
  },
  {
    _id: "br002",
    title: "Brochure - Tri-Fold 8.5\" x 11\" (250 pcs) - 80lb Gloss",
    image: ["/assets/colors/9.jpg"],
    price: 95.00,
    off_price: 125.00,
    discount: 24,
    discountPercentage: 24,
    set: 250,
    stock: 180,
    description: "Premium tri-fold brochure. 80lb gloss text stock with vibrant colors.",
    size: "8.5\" x 11\"",
    category: "printing",
    subCategory: "brochure",
    shape: "rectangular",
  },
  {
    _id: "br003",
    title: "Brochure - Tri-Fold 8.5\" x 14\" (500 pcs) - 100lb Gloss",
    image: ["/assets/colors/9.jpg"],
    price: 220.00,
    off_price: 290.00,
    discount: 24,
    discountPercentage: 24,
    set: 500,
    stock: 120,
    description: "Legal size tri-fold brochure. Extra thick 100lb gloss text for premium feel.",
    size: "8.5\" x 14\"",
    category: "printing",
    subCategory: "brochure",
    shape: "rectangular",
  },

  // Flyers
  {
    _id: "fl001",
    title: "Flyers 8.5\" x 11\" (100 pcs) - 20lb Paper",
    image: ["/assets/colors/10.jpg"],
    price: 20.00,
    off_price: 28.00,
    discount: 29,
    discountPercentage: 29,
    set: 100,
    stock: 400,
    description: "Standard flyers. Economical 20lb paper for mass distribution.",
    size: "8.5\" x 11\"",
    category: "printing",
    subCategory: "flyer",
    shape: "rectangular",
  },
  {
    _id: "fl002",
    title: "Flyers 8.5\" x 11\" (250 pcs) - 28lb Paper",
    image: ["/assets/colors/10.jpg"],
    price: 38.00,
    off_price: 50.00,
    discount: 24,
    discountPercentage: 24,
    set: 250,
    stock: 350,
    description: "Heavier weight flyers. 28lb paper with better durability.",
    size: "8.5\" x 11\"",
    category: "printing",
    subCategory: "flyer",
    shape: "rectangular",
  },
  {
    _id: "fl003",
    title: "Flyers 8.5\" x 11\" (500 pcs) - 80lb Gloss Text",
    image: ["/assets/colors/10.jpg"],
    price: 95.00,
    off_price: 125.00,
    discount: 24,
    discountPercentage: 24,
    set: 500,
    stock: 280,
    description: "Premium glossy flyers. 80lb gloss text with professional finish.",
    size: "8.5\" x 11\"",
    category: "printing",
    subCategory: "flyer",
    shape: "rectangular",
  },
  {
    _id: "fl004",
    title: "Flyers 8.5\" x 11\" (1000 pcs) - 100lb Gloss Text",
    image: ["/assets/colors/10.jpg"],
    price: 175.00,
    off_price: 230.00,
    discount: 24,
    discountPercentage: 24,
    set: 1000,
    stock: 220,
    description: "Extra thick glossy flyers. 100lb gloss text for maximum impact.",
    size: "8.5\" x 11\"",
    category: "printing",
    subCategory: "flyer",
    shape: "rectangular",
  },
  {
    _id: "fl005",
    title: "Flyers 8.5\" x 11\" (500 pcs) - 80lb Cover",
    image: ["/assets/colors/10.jpg"],
    price: 120.00,
    off_price: 160.00,
    discount: 25,
    discountPercentage: 25,
    set: 500,
    stock: 200,
    description: "Heavy duty flyers. 80lb cover stock with substantial feel.",
    size: "8.5\" x 11\"",
    category: "printing",
    subCategory: "flyer",
    shape: "rectangular",
  },
  {
    _id: "fl006",
    title: "Flyers 8.5\" x 11\" (1000 pcs) - 100lb Cover",
    image: ["/assets/colors/10.jpg"],
    price: 220.00,
    off_price: 290.00,
    discount: 24,
    discountPercentage: 24,
    set: 1000,
    stock: 180,
    description: "Extra thick premium flyers. 100lb cover stock for luxury presentations.",
    size: "8.5\" x 11\"",
    category: "printing",
    subCategory: "flyer",
    shape: "rectangular",
  },

  // Presentation Folders
  {
    _id: "pf001",
    title: "Presentation Folder - Two Pocket",
    image: ["/assets/colors/11.jpg"],
    price: 135.00,
    off_price: 180.00,
    discount: 25,
    discountPercentage: 25,
    set: 100,
    stock: 150,
    description: "Professional presentation folder. 14pt stock with UV gloss, two pockets.",
    size: "9\" x 12\"",
    category: "printing",
    subCategory: "presentationfolder",
    shape: "rectangular",
  },
  {
    _id: "pf002",
    title: "Presentation Folder - Business Card Slits",
    image: ["/assets/colors/11.jpg"],
    price: 155.00,
    off_price: 205.00,
    discount: 24,
    discountPercentage: 24,
    set: 100,
    stock: 120,
    description: "Deluxe folder with business card slits. Make a lasting impression.",
    size: "9\" x 12\"",
    category: "printing",
    subCategory: "presentationfolder",
    shape: "rectangular",
  },

  // Saddle Stitch Booklet & Newsletter
  {
    _id: "ss001",
    title: "Saddle Stitch Booklet - 8 Pages",
    image: ["/assets/colors/12.jpg"],
    price: 85.00,
    off_price: 115.00,
    discount: 26,
    discountPercentage: 26,
    set: 100,
    description: "8-page saddle stitched booklet. 80lb text interior with 100lb cover.",
    size: "8.5\" x 11\"",
    category: "printing",
    subCategory: "booklet",
    shape: "rectangular",
  },
  {
    _id: "ss002",
    title: "Saddle Stitch Booklet - 16 Pages",
    image: ["/assets/colors/12.jpg"],
    price: 145.00,
    off_price: 195.00,
    discount: 26,
    discountPercentage: 26,
    set: 100,
    stock: 100,
    description: "16-page booklet. Perfect for product catalogs and newsletters.",
    size: "8.5\" x 11\"",
    category: "printing",
    subCategory: "booklet",
    shape: "rectangular",
  },
  {
    _id: "ss003",
    title: "Newsletter - 4 Pages",
    image: ["/assets/colors/12.jpg"],
    price: 55.00,
    off_price: 75.00,
    discount: 27,
    discountPercentage: 27,
    set: 100,
    stock: 200,
    description: "Four-page newsletter. 80lb text stock, folded in half.",
    size: "8.5\" x 11\"",
    category: "printing",
    subCategory: "newsletter",
    shape: "rectangular",
  },

  // Perfect Binding
  {
    _id: "pb001",
    title: "Perfect Bound Book - 50 Pages",
    image: ["/assets/colors/12.jpg"],
    price: 280.00,
    off_price: 370.00,
    discount: 24,
    discountPercentage: 24,
    set: 100,
    stock: 80,
    description: "Perfect bound book. Professional square spine binding, 50-page interior.",
    size: "8.5\" x 11\"",
    category: "printing",
    subCategory: "perfectbinding",
    shape: "rectangular",
  },
  {
    _id: "pb002",
    title: "Perfect Bound Book - 100 Pages",
    image: ["/assets/colors/12.jpg"],
    price: 450.00,
    off_price: 600.00,
    discount: 25,
    discountPercentage: 25,
    set: 100,
    stock: 60,
    description: "Thick perfect bound book. 100-page interior with premium cover stock.",
    size: "8.5\" x 11\"",
    category: "printing",
    subCategory: "perfectbinding",
    shape: "rectangular",
  },

  // Carbonless Forms / NCR
  {
    _id: "cf001",
    title: "Carbonless Forms - 2-Part (100 sets)",
    image: ["/assets/colors/13.jpg"],
    price: 85.00,
    off_price: 115.00,
    discount: 26,
    discountPercentage: 26,
    set: 100,
    stock: 150,
    description: "Two-part carbonless forms. White/canary with sequential numbering.",
    size: "8.5\" x 11\"",
    category: "printing",
    subCategory: "carbonless",
    shape: "rectangular",
  },
  {
    _id: "cf002",
    title: "Carbonless Forms - 3-Part (250 sets)",
    image: ["/assets/colors/13.jpg"],
    price: 190.00,
    off_price: 250.00,
    discount: 24,
    discountPercentage: 24,
    set: 250,
    stock: 120,
    description: "Three-part NCR forms. White/canary/pink with custom printing.",
    size: "8.5\" x 11\"",
    category: "printing",
    subCategory: "carbonless",
    shape: "rectangular",
  },

  // Label / Paper Stickers
  {
    _id: "lb001",
    title: "Paper Labels - 2\" x 2\" (100 pcs)",
    image: ["/assets/colors/18.jpg"],
    price: 22.00,
    off_price: 30.00,
    discount: 27,
    discountPercentage: 27,
    set: 100,
    stock: 300,
    description: "Square paper labels. Permanent adhesive, full color printing.",
    size: "2\" x 2\"",
    category: "printing",
    subCategory: "paperlabel",
    shape: "square",
  },
  {
    _id: "lb002",
    title: "Paper Labels - 3\" x 4\" (250 pcs)",
    image: ["/assets/colors/18.jpg"],
    price: 55.00,
    off_price: 75.00,
    discount: 27,
    discountPercentage: 27,
    set: 250,
    stock: 250,
    description: "Rectangular paper labels. Great for product packaging and mailings.",
    size: "3\" x 4\"",
    category: "printing",
    subCategory: "paperlabel",
    shape: "rectangular",
  },

  // Vinyl Stickers
  {
    _id: "vs001",
    title: "Vinyl Stickers - 2\" x 2\" (100 pcs)",
    image: ["/assets/colors/18.jpg"],
    price: 46.00,
    off_price: 62.00,
    discount: 26,
    discountPercentage: 26,
    set: 100,
    stock: 200,
    description: "Durable vinyl stickers. Waterproof and weather-resistant.",
    size: "2\" x 2\"",
    category: "printing",
    subCategory: "vinylsticker",
    shape: "square",
  },
  {
    _id: "vs002",
    title: "Vinyl Stickers - 3\" x 3\" (250 pcs)",
    image: ["/assets/colors/18.jpg"],
    price: 95.00,
    off_price: 125.00,
    discount: 24,
    discountPercentage: 24,
    set: 250,
    stock: 180,
    description: "Medium vinyl stickers. Perfect for outdoor use and promotions.",
    size: "3\" x 3\"",
    category: "printing",
    subCategory: "vinylsticker",
    shape: "square",
  },
  {
    _id: "vs003",
    title: "Vinyl Stickers - 4\" x 6\" (500 pcs)",
    image: ["/assets/colors/18.jpg"],
    price: 240.00,
    off_price: 320.00,
    discount: 25,
    discountPercentage: 25,
    set: 500,
    stock: 140,
    description: "Large vinyl stickers. High-quality UV printing for vibrant colors.",
    size: "4\" x 6\"",
    category: "printing",
    subCategory: "vinylsticker",
    shape: "rectangular",
  },

  // Metallic Stickers - Silver
  {
    _id: "ms001",
    title: "Silver Metallic Stickers - 1\" x 1\" (100 pcs)",
    image: ["/assets/colors/18.jpg"],
    price: 36.00,
    off_price: 48.00,
    discount: 25,
    discountPercentage: 25,
    set: 100,
    stock: 200,
    description: "Waterproof silver vinyl stickers. Premium metallic finish.",
    size: "1\" x 1\"",
    category: "printing",
    subCategory: "metallicsticker",
    shape: "square",
  },
  {
    _id: "ms002",
    title: "Silver Metallic Stickers - 2\" x 2\" (250 pcs)",
    image: ["/assets/colors/18.jpg"],
    price: 106.00,
    off_price: 140.00,
    discount: 24,
    discountPercentage: 24,
    set: 250,
    stock: 150,
    description: "Medium silver stickers. Perfect for branding and packaging.",
    size: "2\" x 2\"",
    category: "printing",
    subCategory: "metallicsticker",
    shape: "square",
  },
  {
    _id: "ms003",
    title: "Silver Metallic Stickers - 3\" x 3\" (500 pcs)",
    image: ["/assets/colors/18.jpg"],
    price: 336.00,
    off_price: 445.00,
    discount: 24,
    discountPercentage: 24,
    set: 500,
    stock: 100,
    description: "Large silver metallic stickers. High-quality waterproof vinyl.",
    size: "3\" x 3\"",
    category: "printing",
    subCategory: "metallicsticker",
    shape: "square",
  },

  // Gold Metallic Stickers
  {
    _id: "ms004",
    title: "Gold Metallic Stickers - 1\" x 1\" (100 pcs)",
    image: ["/assets/colors/19.jpg"],
    price: 36.00,
    off_price: 48.00,
    discount: 25,
    discountPercentage: 25,
    set: 100,
    stock: 180,
    description: "Premium gold vinyl stickers. Waterproof and durable.",
    size: "1\" x 1\"",
    category: "printing",
    subCategory: "metallicsticker",
    shape: "square",
  },
  {
    _id: "ms005",
    title: "Gold Metallic Stickers - 3\" x 4\" (250 pcs)",
    image: ["/assets/colors/19.jpg"],
    price: 174.00,
    off_price: 230.00,
    discount: 24,
    discountPercentage: 24,
    set: 250,
    stock: 120,
    description: "Elegant gold stickers. Perfect for premium product labels.",
    size: "3\" x 4\"",
    category: "printing",
    subCategory: "metallicsticker",
    shape: "rectangular",
  },

  // Holographic Stickers
  {
    _id: "ms006",
    title: "Holographic Stickers - 2\" x 2\" (100 pcs)",
    image: ["/assets/colors/20.jpg"],
    price: 46.00,
    off_price: 62.00,
    discount: 26,
    discountPercentage: 26,
    set: 100,
    stock: 140,
    description: "Eye-catching holographic stickers. Rainbow effect finish.",
    size: "2\" x 2\"",
    category: "printing",
    subCategory: "metallicsticker",
    shape: "square",
  },
  {
    _id: "ms007",
    title: "Holographic Stickers - 4\" x 4\" (500 pcs)",
    image: ["/assets/colors/20.jpg"],
    price: 594.00,
    off_price: 785.00,
    discount: 24,
    discountPercentage: 24,
    set: 500,
    stock: 80,
    description: "Large holographic stickers with stunning rainbow finish.",
    size: "4\" x 4\"",
    category: "printing",
    subCategory: "metallicsticker",
    shape: "square",
  },

  // Greeting Cards / Invitations / Rackcards
  {
    _id: "gc001",
    title: "Greeting Cards - 5\" x 7\" (100 pcs)",
    image: ["/assets/colors/6.jpg"],
    price: 85.00,
    off_price: 115.00,
    discount: 26,
    discountPercentage: 26,
    set: 100,
    stock: 200,
    description: "Custom greeting cards with envelopes. 14pt cardstock with UV coating.",
    size: "5\" x 7\"",
    category: "printing",
    subCategory: "greetingcard",
    shape: "rectangular",
  },
  {
    _id: "gc002",
    title: "Wedding Invitation Cards (100 pcs)",
    image: ["/assets/colors/6.jpg"],
    price: 0.40,
    off_price: 0.70,
    discount: 43,
    discountPercentage: 43,
    set: 100,
    stock: 300,
    description: "Elegant wedding invitation cards with custom design. Premium cardstock.",
    size: "5\" x 7\"",
    category: "printing",
    subCategory: "invitation",
    shape: "rectangular",
  },
  {
    _id: "gc003",
    title: "Event Invitation Cards (250 pcs)",
    image: ["/assets/colors/6.jpg"],
    price: 0.35,
    off_price: 0.60,
    discount: 42,
    discountPercentage: 42,
    set: 250,
    stock: 250,
    description: "Professional event invitations. High-quality printing on premium stock.",
    size: "5\" x 7\"",
    category: "printing",
    subCategory: "invitation",
    shape: "rectangular",
  },
  {
    _id: "gc004",
    title: "Rack Cards - 4\" x 9\" (250 pcs)",
    image: ["/assets/colors/10.jpg"],
    price: 65.00,
    off_price: 85.00,
    discount: 24,
    discountPercentage: 24,
    set: 250,
    stock: 180,
    description: "Eye-catching rack cards. 14pt cardstock with UV gloss for displays.",
    size: "4\" x 9\"",
    category: "printing",
    subCategory: "rackcard",
    shape: "rectangular",
  },

  // Hand Fans
  {
    _id: "hf001",
    title: "Hand Fans - Custom Printed (100 pcs)",
    image: ["/assets/colors/11.jpg"],
    price: 75.00,
    off_price: 100.00,
    discount: 25,
    discountPercentage: 25,
    set: 100,
    stock: 150,
    description: "Custom printed hand fans. Perfect for weddings and outdoor events.",
    size: "8\" x 8\"",
    category: "printing",
    subCategory: "handfan",
    shape: "custom",
  },

  // Tickets / Bookmarks
  {
    _id: "tk001",
    title: "Event Tickets - Perforated (500 pcs)",
    image: ["/assets/colors/13.jpg"],
    price: 55.00,
    off_price: 75.00,
    discount: 27,
    discountPercentage: 27,
    set: 500,
    stock: 200,
    description: "Custom event tickets with perforation. Sequential numbering included.",
    size: "2\" x 5.5\"",
    category: "printing",
    subCategory: "ticket",
    shape: "rectangular",
  },
  {
    _id: "tk002",
    title: "Raffle Tickets - 2 Part (1000 pcs)",
    image: ["/assets/colors/13.jpg"],
    price: 85.00,
    off_price: 115.00,
    discount: 26,
    discountPercentage: 26,
    set: 1000,
    stock: 180,
    description: "Two-part raffle tickets. Perforated with matching numbers.",
    size: "2\" x 5.5\"",
    category: "printing",
    subCategory: "ticket",
    shape: "rectangular",
  },
  {
    _id: "tk003",
    title: "Bookmarks - 2\" x 6\" (250 pcs)",
    image: ["/assets/colors/11.jpg"],
    price: 45.00,
    off_price: 60.00,
    discount: 25,
    discountPercentage: 25,
    set: 250,
    stock: 220,
    description: "Custom bookmarks. 14pt cardstock with UV gloss or matte finish.",
    size: "2\" x 6\"",
    category: "printing",
    subCategory: "bookmark",
    shape: "rectangular",
  },

  // Letterheads & Envelopes
  {
    _id: "lh001",
    title: "Letterhead - 8.5\" x 11\" (500 sheets)",
    image: ["/assets/colors/13.jpg"],
    price: 65.00,
    off_price: 85.00,
    discount: 24,
    discountPercentage: 24,
    set: 500,
    stock: 200,
    description: "Professional letterhead. 70lb uncoated text stock, full color.",
    size: "8.5\" x 11\"",
    category: "printing",
    subCategory: "letterhead",
    shape: "rectangular",
  },
  {
    _id: "lh002",
    title: "#10 Envelopes - Full Color (500 pcs)",
    image: ["/assets/colors/13.jpg"],
    price: 95.00,
    off_price: 125.00,
    discount: 24,
    discountPercentage: 24,
    set: 500,
    stock: 180,
    description: "Standard business envelopes. Full color printing on 24lb paper.",
    size: "4.125\" x 9.5\"",
    category: "printing",
    subCategory: "envelope",
    shape: "rectangular",
  },

  // Notepads
  {
    _id: "np001",
    title: "Notepad - 50 Sheets (25 pads)",
    image: ["/assets/colors/13.jpg"],
    price: 65.00,
    off_price: 85.00,
    discount: 24,
    discountPercentage: 24,
    set: 25,
    stock: 150,
    description: "Custom notepad. 50 sheets per pad, chipboard backing.",
    size: "4.25\" x 5.5\"",
    category: "printing",
    subCategory: "notepad",
    shape: "rectangular",
  },
  {
    _id: "np002",
    title: "Notepad - 100 Sheets (50 pads)",
    image: ["/assets/colors/13.jpg"],
    price: 120.00,
    off_price: 160.00,
    discount: 25,
    discountPercentage: 25,
    set: 50,
    stock: 120,
    description: "Large notepad set. 100 sheets per pad with custom header.",
    size: "5.5\" x 8.5\"",
    category: "printing",
    subCategory: "notepad",
    shape: "rectangular",
  },

  // Door Hangers / Rigid Polyester Menus
  {
    _id: "dh001",
    title: "Door Hangers - 4.25\" x 11\" (250 pcs)",
    image: ["/assets/colors/11.jpg"],
    price: 75.00,
    off_price: 100.00,
    discount: 25,
    discountPercentage: 25,
    set: 250,
    stock: 180,
    description: "Die-cut door hangers. 14pt cardstock with UV gloss coating.",
    size: "4.25\" x 11\"",
    category: "printing",
    subCategory: "doorhanger",
    shape: "rectangular",
  },
  {
    _id: "dh002",
    title: "Rigid Polyester Menu - 8.5\" x 11\"",
    image: ["/assets/colors/11.jpg"],
    price: 95.00,
    off_price: 125.00,
    discount: 24,
    discountPercentage: 24,
    set: 50,
    stock: 100,
    description: "Waterproof restaurant menu. Rigid polyester material, full color.",
    size: "8.5\" x 11\"",
    category: "printing",
    subCategory: "menu",
    shape: "rectangular",
  },
  {
    _id: "dh003",
    title: "Rigid Polyester Menu - 11\" x 17\"",
    image: ["/assets/colors/11.jpg"],
    price: 150.00,
    off_price: 200.00,
    discount: 25,
    discountPercentage: 25,
    set: 50,
    stock: 80,
    description: "Large restaurant menu. Durable polyester, wipeable surface.",
    size: "11\" x 17\"",
    category: "printing",
    subCategory: "menu",
    shape: "rectangular",
  },

  // ============ OTHER PRODUCTS ============
  
  // ============ OTHER PRODUCTS ============
  
  // Self Ink Stamps
  {
    _id: "st001",
    title: "Self-Inking Stamp 1438 - 0.54\" x 1.49\"",
    image: ["/assets/colors/2.jpg"],
    price: 37.90,
    off_price: 50.00,
    discount: 24,
    discountPercentage: 24,
    set: 1,
    stock: 75,
    description: "Compact self-inking rubber stamp. Perfect for small logos and text.",
    size: "0.54\" x 1.49\"",
    category: "otherproducts",
    subCategory: "stamp",
    shape: "rectangular",
  },
  {
    _id: "st002",
    title: "Self-Inking Stamp 1850 - 0.71\" x 1.97\"",
    image: ["/assets/colors/2.jpg"],
    price: 43.90,
    off_price: 58.00,
    discount: 24,
    discountPercentage: 24,
    set: 1,
    stock: 70,
    description: "Medium size self-inking stamp. Ideal for addresses and signatures.",
    size: "0.71\" x 1.97\"",
    category: "otherproducts",
    subCategory: "stamp",
    shape: "rectangular",
  },
  {
    _id: "st003",
    title: "Self-Inking Stamp 2260 - 0.86\" x 2.35\"",
    image: ["/assets/colors/2.jpg"],
    price: 59.90,
    off_price: 78.00,
    discount: 23,
    discountPercentage: 23,
    set: 1,
    stock: 60,
    description: "Large self-inking stamp. Great for detailed designs and multiple lines.",
    size: "0.86\" x 2.35\"",
    category: "otherproducts",
    subCategory: "stamp",
    shape: "rectangular",
  },
  {
    _id: "st004",
    title: "Self-Inking Stamp 2770 - 1.04\" x 2.75\"",
    image: ["/assets/colors/2.jpg"],
    price: 59.90,
    off_price: 78.00,
    discount: 23,
    discountPercentage: 23,
    set: 1,
    stock: 55,
    description: "Extra large self-inking stamp. Maximum impression area.",
    size: "1.04\" x 2.75\"",
    category: "otherproducts",
    subCategory: "stamp",
    shape: "rectangular",
  },
  {
    _id: "st005",
    title: "Notary Stamp 3030 - 1.18\" x 1.18\"",
    image: ["/assets/colors/2.jpg"],
    price: 45.90,
    off_price: 60.00,
    discount: 24,
    discountPercentage: 24,
    set: 1,
    stock: 50,
    description: "Official notary public self-inking stamp. Customizable with your details.",
    size: "1.18\" x 1.18\"",
    category: "otherproducts",
    subCategory: "stamp",
    shape: "square",
  },
  {
    _id: "st006",
    title: "Notary Stamp 4040 - 1.58\" x 1.58\"",
    image: ["/assets/colors/2.jpg"],
    price: 59.90,
    off_price: 78.00,
    discount: 23,
    discountPercentage: 23,
    set: 1,
    stock: 45,
    description: "Large notary public stamp. Professional quality with clear impressions.",
    size: "1.58\" x 1.58\"",
    category: "otherproducts",
    subCategory: "stamp",
    shape: "square",
  },

  // Name / ID Badges / Metal Badges
  {
    _id: "bg001",
    title: "Name Badge - Plastic with Pin (10 pcs)",
    image: ["/assets/colors/1.jpg"],
    price: 35.00,
    off_price: 48.00,
    discount: 27,
    discountPercentage: 27,
    set: 10,
    stock: 200,
    description: "Professional name badges. Full color printing on plastic with pin attachment.",
    size: "3\" x 1\"",
    category: "otherproducts",
    subCategory: "badge",
    shape: "rectangular",
  },
  {
    _id: "bg002",
    title: "Name Badge - Magnetic Back (25 pcs)",
    image: ["/assets/colors/1.jpg"],
    price: 75.00,
    off_price: 100.00,
    discount: 25,
    discountPercentage: 25,
    set: 25,
    stock: 150,
    description: "Magnetic name badges. No pins needed, strong magnetic backing.",
    size: "3\" x 1\"",
    category: "otherproducts",
    subCategory: "badge",
    shape: "rectangular",
  },
  {
    _id: "bg003",
    title: "Metal Name Badge - Engraved",
    image: ["/assets/colors/1.jpg"],
    price: 18.00,
    off_price: 25.00,
    discount: 28,
    discountPercentage: 28,
    set: 1,
    stock: 180,
    description: "Premium metal badge with laser engraving. Durable and professional.",
    size: "3\" x 1\"",
    category: "otherproducts",
    subCategory: "badge",
    shape: "rectangular",
  },

  // Trophies / Medals / Mugs / Tumblers
  {
    _id: "tr001",
    title: "Custom Trophy - Small",
    image: ["/assets/colors/16.jpg"],
    price: 35.00,
    off_price: 48.00,
    discount: 27,
    discountPercentage: 27,
    set: 1,
    stock: 80,
    description: "Customizable trophy with engraving. Perfect for awards and recognition.",
    size: "6 inches tall",
    category: "otherproducts",
    subCategory: "trophy",
    shape: "custom",
  },
  {
    _id: "tr002",
    title: "Custom Trophy - Large",
    image: ["/assets/colors/16.jpg"],
    price: 65.00,
    off_price: 85.00,
    discount: 24,
    discountPercentage: 24,
    set: 1,
    stock: 60,
    description: "Large trophy with custom engraving. Impressive award presentation.",
    size: "12 inches tall",
    category: "otherproducts",
    subCategory: "trophy",
    shape: "custom",
  },
  {
    _id: "md001",
    title: "Custom Medal with Ribbon",
    image: ["/assets/colors/17.jpg"],
    price: 20.00,
    off_price: 28.00,
    discount: 29,
    discountPercentage: 29,
    set: 1,
    stock: 150,
    description: "Personalized medal with custom ribbon. Ideal for sports and events.",
    size: "2.5 inches",
    category: "otherproducts",
    subCategory: "medal",
    shape: "circular",
  },
  {
    _id: "md002",
    title: "Gold Medal with Custom Engraving",
    image: ["/assets/colors/17.jpg"],
    price: 28.00,
    off_price: 38.00,
    discount: 26,
    discountPercentage: 26,
    set: 1,
    stock: 120,
    description: "Premium gold-finish medal. Custom engraving on back with neck ribbon.",
    size: "3 inches",
    category: "otherproducts",
    subCategory: "medal",
    shape: "circular",
  },
  {
    _id: "mg001",
    title: "Custom Photo Mug - 11 oz",
    image: ["/assets/colors/3.jpg"],
    price: 15.90,
    off_price: 22.00,
    discount: 28,
    discountPercentage: 28,
    set: 1,
    stock: 150,
    description: "Personalized ceramic mug with your photo or design. Microwave and dishwasher safe.",
    size: "11 oz",
    category: "otherproducts",
    subCategory: "mug",
    shape: "circular",
  },
  {
    _id: "mg002",
    title: "Custom Photo Mug - 15 oz",
    image: ["/assets/colors/3.jpg"],
    price: 18.90,
    off_price: 26.00,
    discount: 27,
    discountPercentage: 27,
    set: 1,
    stock: 130,
    description: "Large ceramic mug with custom printing. Perfect for coffee lovers.",
    size: "15 oz",
    category: "otherproducts",
    subCategory: "mug",
    shape: "circular",
  },
  {
    _id: "tb001",
    title: "Custom Tumbler - Full Color",
    image: ["/assets/colors/14.jpg"],
    price: 35.00,
    off_price: 48.00,
    discount: 27,
    discountPercentage: 27,
    set: 1,
    stock: 100,
    description: "Insulated stainless steel tumbler with full color printing. Keeps drinks hot or cold.",
    size: "20 oz",
    category: "otherproducts",
    subCategory: "tumbler",
    shape: "circular",
  },
  {
    _id: "tb002",
    title: "Custom Tumbler - Engraved",
    image: ["/assets/colors/14.jpg"],
    price: 38.00,
    off_price: 52.00,
    discount: 27,
    discountPercentage: 27,
    set: 1,
    stock: 90,
    description: "Premium engraved stainless steel tumbler. Elegant and durable.",
    size: "20 oz",
    category: "otherproducts",
    subCategory: "tumbler",
    shape: "circular",
  },
  {
    _id: "tb003",
    title: "Insulated Tumbler - 30 oz",
    image: ["/assets/colors/14.jpg"],
    price: 45.00,
    off_price: 60.00,
    discount: 25,
    discountPercentage: 25,
    set: 1,
    stock: 80,
    description: "Large capacity tumbler. Double-wall insulation with custom design.",
    size: "30 oz",
    category: "otherproducts",
    subCategory: "tumbler",
    shape: "circular",
  },

  // Print Station Kit
  {
    _id: "ps001",
    title: "Print Station Starter Kit",
    image: ["/assets/colors/11.jpg"],
    price: 450.00,
    off_price: 600.00,
    discount: 25,
    discountPercentage: 25,
    set: 1,
    stock: 25,
    description: "Complete print station kit with supplies. Start your own printing business.",
    size: "Starter Package",
    category: "otherproducts",
    subCategory: "printkit",
    shape: "rectangular",
  },
  {
    _id: "ps002",
    title: "Print Station Pro Kit",
    image: ["/assets/colors/11.jpg"],
    price: 850.00,
    off_price: 1100.00,
    discount: 23,
    discountPercentage: 23,
    set: 1,
    stock: 15,
    description: "Professional print station with advanced equipment. Everything you need.",
    size: "Professional Package",
    category: "otherproducts",
    subCategory: "printkit",
    shape: "rectangular",
  },

  // Granite Photo Slates
  {
    _id: "gps001",
    title: "Granite Photo Slate - 6x8 inch",
    image: ["/assets/colors/15.jpg"],
    price: 30.00,
    off_price: 42.00,
    discount: 29,
    discountPercentage: 29,
    set: 1,
    stock: 70,
    description: "Custom photo printed on granite slate. Perfect memorial or gift item.",
    size: "6 x 8 inches",
    category: "otherproducts",
    subCategory: "photoslate",
    shape: "rectangular",
  },
  {
    _id: "gps002",
    title: "Granite Photo Slate - 8x12 inch",
    image: ["/assets/colors/15.jpg"],
    price: 40.00,
    off_price: 55.00,
    discount: 27,
    discountPercentage: 27,
    set: 1,
    stock: 60,
    description: "Large granite photo slate. Beautiful keepsake with custom photo.",
    size: "8 x 12 inches",
    category: "otherproducts",
    subCategory: "photoslate",
    shape: "rectangular",
  },
  {
    _id: "gps003",
    title: "Granite Photo Slate - Heart 8x8 inch",
    image: ["/assets/colors/15.jpg"],
    price: 36.00,
    off_price: 50.00,
    discount: 28,
    discountPercentage: 28,
    set: 1,
    stock: 55,
    description: "Heart-shaped granite photo slate. Romantic memorial or gift.",
    size: "8 x 8 inches",
    category: "otherproducts",
    subCategory: "photoslate",
    shape: "heart",
  },
  {
    _id: "gps004",
    title: "Granite Photo Slate - Circle 6x6 inch",
    image: ["/assets/colors/15.jpg"],
    price: 36.00,
    off_price: 50.00,
    discount: 28,
    discountPercentage: 28,
    set: 1,
    stock: 50,
    description: "Circular granite photo slate with stand. Unique display piece.",
    size: "6 x 6 inches",
    category: "otherproducts",
    subCategory: "photoslate",
    shape: "circular",
  },

  // Pens
  {
    _id: "pn001",
    title: "Custom Printed Pens (100 pcs)",
    image: ["/assets/colors/1.jpg"],
    price: 65.00,
    off_price: 85.00,
    discount: 24,
    discountPercentage: 24,
    set: 100,
    stock: 200,
    description: "Custom printed ballpoint pens. Great for promotions and giveaways.",
    size: "Standard",
    category: "otherproducts",
    subCategory: "pen",
    shape: "cylindrical",
  },
  {
    _id: "pn002",
    title: "Premium Metal Pens (50 pcs)",
    image: ["/assets/colors/1.jpg"],
    price: 95.00,
    off_price: 125.00,
    discount: 24,
    discountPercentage: 24,
    set: 50,
    stock: 150,
    description: "Engraved metal pens. Luxury feel for corporate gifts and awards.",
    size: "Executive",
    category: "otherproducts",
    subCategory: "pen",
    shape: "cylindrical",
  },
  {
    _id: "pn003",
    title: "Stylus Pens with Logo (250 pcs)",
    image: ["/assets/colors/1.jpg"],
    price: 180.00,
    off_price: 240.00,
    discount: 25,
    discountPercentage: 25,
    set: 250,
    stock: 120,
    description: "Multi-function stylus pens. Works on touchscreens with custom logo.",
    size: "Standard",
    category: "otherproducts",
    subCategory: "pen",
    shape: "cylindrical",
  },

  // ============ APPAREL ============
  
  // Custom T-Shirts
  {
    _id: "ts001",
    title: "Custom T-Shirt - Basic Cotton",
    image: ["/assets/colors/4.jpg"],
    price: 18.00,
    off_price: 25.00,
    discount: 28,
    discountPercentage: 28,
    set: 1,
    stock: 200,
    description: "High-quality custom t-shirt with your design. 100% cotton, various sizes.",
    size: "S, M, L, XL, XXL",
    category: "apparel",
    subCategory: "tshirt",
    shape: "rectangular",
  },
  {
    _id: "ts002",
    title: "Custom T-Shirt - Premium Tri-Blend",
    image: ["/assets/colors/4.jpg"],
    price: 26.00,
    off_price: 35.00,
    discount: 26,
    discountPercentage: 26,
    set: 1,
    stock: 180,
    description: "Premium tri-blend t-shirt. Ultra-soft with superior print quality.",
    size: "S, M, L, XL, XXL",
    category: "apparel",
    subCategory: "tshirt",
    shape: "rectangular",
  },
  {
    _id: "ts003",
    title: "Performance T-Shirt - Moisture Wicking",
    image: ["/assets/colors/4.jpg"],
    price: 28.00,
    off_price: 38.00,
    discount: 26,
    discountPercentage: 26,
    set: 1,
    stock: 150,
    description: "Athletic performance tee. Moisture-wicking fabric with custom design.",
    size: "S, M, L, XL, XXL",
    category: "apparel",
    subCategory: "tshirt",
    shape: "rectangular",
  },

  // Hoodies
  {
    _id: "hd001",
    title: "Custom Hoodie - Pullover",
    image: ["/assets/colors/4.jpg"],
    price: 48.00,
    off_price: 65.00,
    discount: 26,
    discountPercentage: 26,
    set: 1,
    stock: 120,
    description: "Cozy pullover hoodie with custom printing. 80/20 cotton-poly blend.",
    size: "S, M, L, XL, XXL",
    category: "apparel",
    subCategory: "hoodie",
    shape: "rectangular",
  },
  {
    _id: "hd002",
    title: "Custom Hoodie - Full Zip",
    image: ["/assets/colors/4.jpg"],
    price: 55.00,
    off_price: 75.00,
    discount: 27,
    discountPercentage: 27,
    set: 1,
    stock: 100,
    description: "Full-zip hoodie with custom design. Premium quality with pockets.",
    size: "S, M, L, XL, XXL",
    category: "apparel",
    subCategory: "hoodie",
    shape: "rectangular",
  },

  // Polo Shirts
  {
    _id: "pl001",
    title: "Custom Polo Shirt",
    image: ["/assets/colors/4.jpg"],
    price: 32.00,
    off_price: 45.00,
    discount: 29,
    discountPercentage: 29,
    set: 1,
    stock: 140,
    description: "Professional polo shirt with embroidered logo. 100% cotton pique.",
    size: "S, M, L, XL, XXL",
    category: "apparel",
    subCategory: "polo",
    shape: "rectangular",
  },
  {
    _id: "pl002",
    title: "Performance Polo - Moisture Wicking",
    image: ["/assets/colors/4.jpg"],
    price: 38.00,
    off_price: 52.00,
    discount: 27,
    discountPercentage: 27,
    set: 1,
    stock: 110,
    description: "Athletic polo shirt. Moisture-wicking fabric with custom embroidery.",
    size: "S, M, L, XL, XXL",
    category: "apparel",
    subCategory: "polo",
    shape: "rectangular",
  },

  // Long Sleeve Shirts
  {
    _id: "ls001",
    title: "Custom Long Sleeve T-Shirt",
    image: ["/assets/colors/4.jpg"],
    price: 24.00,
    off_price: 32.00,
    discount: 25,
    discountPercentage: 25,
    set: 1,
    stock: 160,
    description: "Long sleeve cotton tee. Custom design front and back.",
    size: "S, M, L, XL, XXL",
    category: "apparel",
    subCategory: "longsleeve",
    shape: "rectangular",
  },

  // Tank Tops
  {
    _id: "tn001",
    title: "Custom Tank Top",
    image: ["/assets/colors/4.jpg"],
    price: 16.00,
    off_price: 22.00,
    discount: 27,
    discountPercentage: 27,
    set: 1,
    stock: 180,
    description: "Athletic tank top with custom print. Lightweight and breathable.",
    size: "S, M, L, XL, XXL",
    category: "apparel",
    subCategory: "tanktop",
    shape: "rectangular",
  },

  // Jackets
  {
    _id: "jk001",
    title: "Custom Windbreaker Jacket",
    image: ["/assets/colors/4.jpg"],
    price: 65.00,
    off_price: 85.00,
    discount: 24,
    discountPercentage: 24,
    set: 1,
    stock: 80,
    description: "Lightweight windbreaker with custom logo. Water-resistant with lining.",
    size: "S, M, L, XL, XXL",
    category: "apparel",
    subCategory: "jacket",
    shape: "rectangular",
  },
  {
    _id: "jk002",
    title: "Custom Fleece Jacket",
    image: ["/assets/colors/4.jpg"],
    price: 75.00,
    off_price: 100.00,
    discount: 25,
    discountPercentage: 25,
    set: 1,
    stock: 70,
    description: "Warm fleece jacket with embroidered logo. Full-zip with pockets.",
    size: "S, M, L, XL, XXL",
    category: "apparel",
    subCategory: "jacket",
    shape: "rectangular",
  },

  // Hats / Caps
  {
    _id: "ht001",
    title: "Custom Baseball Cap",
    image: ["/assets/colors/4.jpg"],
    price: 18.00,
    off_price: 25.00,
    discount: 28,
    discountPercentage: 28,
    set: 1,
    stock: 200,
    description: "Classic baseball cap with embroidered logo. Adjustable strap.",
    size: "One Size",
    category: "apparel",
    subCategory: "hat",
    shape: "circular",
  },
  {
    _id: "ht002",
    title: "Custom Snapback Hat",
    image: ["/assets/colors/4.jpg"],
    price: 22.00,
    off_price: 30.00,
    discount: 27,
    discountPercentage: 27,
    set: 1,
    stock: 180,
    description: "Trendy snapback with custom embroidery. Flat brim style.",
    size: "One Size",
    category: "apparel",
    subCategory: "hat",
    shape: "circular",
  },
  {
    _id: "ht003",
    title: "Custom Beanie",
    image: ["/assets/colors/4.jpg"],
    price: 16.00,
    off_price: 22.00,
    discount: 27,
    discountPercentage: 27,
    set: 1,
    stock: 160,
    description: "Knit beanie with custom embroidered patch. Warm and stylish.",
    size: "One Size",
    category: "apparel",
    subCategory: "hat",
    shape: "circular",
  },
];
